<a href="https://colab.research.google.com/github/delicate99/Python_ML/blob/main/Regularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Regularization

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Filareth2015/DA_and_ML_Python/master/advertising.csv')

In [3]:
df.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [4]:
X= df.drop('Sales', axis= 1)
y = df["Sales"]

In [5]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

### Polynomial conversion / Train-test split

In [6]:
polynomial_converter = PolynomialFeatures(degree = 3, include_bias = False)
poly_features = polynomial_converter.fit_transform(X)

In [7]:
X_train, X_test, y_train,y_test = train_test_split(poly_features, y, test_size =0.3, random_state =101)

### Scaling the Data

In [8]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
X_train = scaler.transform(X_train)
X_test =scaler.transform(X_test)

## Ridge_Regression

In [10]:
from sklearn.linear_model import Ridge

In [11]:
ridge_model = Ridge(alpha =10)

In [12]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='auto', tol=0.001)

In [13]:
test_predictions = ridge_model.predict(X_test)

In [14]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [15]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [16]:
MAE

0.5774404204714162

In [17]:
RMSE

0.8946386461319651

### Choosing an alpha value with Cross Validation

In [18]:
from sklearn.linear_model import RidgeCV

In [19]:
# Choosing a scoring: https://scikit-learn.org/stable/modules/model_evaluation.html
# Negative RMSE so all metrics follow convention "Higher is better"

# See all options: sklearn.metrics.SCORERS.keys()
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0),scoring='neg_mean_absolute_error')

In [20]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=None, fit_intercept=True,
        gcv_mode=None, normalize=False, scoring='neg_mean_absolute_error',
        store_cv_values=False)

In [21]:
ridge_cv_model.alpha_

0.1

In [22]:
from sklearn.metrics import SCORERS

In [23]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [24]:
test_predictions = ridge_cv_model.predict(X_test)

In [25]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [26]:
MAE

0.4273774884345439

In [27]:
RMSE

0.6180719926946001

In [28]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

### Lasso Regularization

In [29]:
from sklearn.linear_model import LassoCV

In [30]:
lasso_cv_model = LassoCV(eps= 0.001, n_alphas =100, cv=5, max_iter= 1000000)

In [31]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(alphas=None, copy_X=True, cv=5, eps=0.001, fit_intercept=True,
        max_iter=1000000, n_alphas=100, n_jobs=None, normalize=False,
        positive=False, precompute='auto', random_state=None,
        selection='cyclic', tol=0.0001, verbose=False)

In [32]:
round(lasso_cv_model.alpha_ , 4)

0.0049

In [33]:
lasso_prediction = lasso_cv_model.predict(X_test)

In [34]:
MAE = mean_absolute_error(y_test,lasso_prediction)
MSE = mean_squared_error(y_test,lasso_prediction)
RMSE = np.sqrt(MSE)

In [35]:
print(MAE)
RMSE

0.4335034618590078


0.6063140748984043

In [36]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

### Elastic-Net

In [37]:
from sklearn.linear_model import ElasticNetCV

In [38]:
elastic_cv_model = ElasticNetCV(l1_ratio=[0.1,.5, .7, .9, .95, .99, 1], eps=0.001, n_alphas =100,max_iter = 10000000)

In [39]:
elastic_cv_model.fit(X_train,y_train)

ElasticNetCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
             l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=10000000,
             n_alphas=100, n_jobs=None, normalize=False, positive=False,
             precompute='auto', random_state=None, selection='cyclic',
             tol=0.0001, verbose=0)

In [40]:
elastic_cv_model.l1_ratio_ # Lasso 100% model is the best fit 

1.0

In [41]:
elastic_cv_model.alpha_ # exactly same with the Lasso model alpha

0.004943070909225833

In [42]:
elastic_predictions = elastic_cv_model.predict(X_test)

In [43]:
MAE = mean_absolute_error(y_test,elastic_predictions)
MSE = mean_squared_error(y_test,elastic_predictions)
RMSE = np.sqrt(MSE)

In [44]:
print(MAE)
RMSE

0.4335034618590078


0.6063140748984043

In [45]:
elastic_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])